version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:8.0"
    restart: always
    networks:
      springapimysql-net:
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: grocery_db
      MYSQL_ROOT_PASSWORD: root

  api_service:
    container_name: grocery-management-service
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      springapimysql-net:
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/grocery_db?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

networks:
  springapimysql-net: